blank_issues_enabled: false
contact_links:
  - name: Community Discussions
    url: https://github.com/democratize-technology/decision-matrix-mcp/discussions
    about: Ask questions and discuss ideas with the community
  - name: Documentation
    url: https://github.com/democratize-technology/decision-matrix-mcp#readme
    about: Check out our documentation for usage guides and examples